# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RPMwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class RPMQT(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(609, 455)
        self.frame = QFrame(Form)
        self.frame.setGeometry(QRect(10, 10, 320, 320))
        self.frame.setFrameShape(QFrame.NoFrame)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setGeometry(QRect(15, 15, 290, 290))
        self.frame_2.setStyleSheet("QFrame{\n"
"\n"
"border-radius: 145px;\n"
"    background-color: rgb(247, 247, 247);\n"
"\n"
"}")
        self.frame_2.setFrameShape(QFrame.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QFrame(self.frame)
        self.frame_3.setGeometry(QRect(10, 10, 300, 300))
        self.frame_3.setStyleSheet("QFrame{\n"
"\n"
"border-radius: 150px;\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.frame_3.setFrameShape(QFrame.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QFrame(self.frame)
        self.frame_4.setGeometry(QRect(10, 10, 300, 300))
        self.frame_4.setStyleSheet("QFrame{\n"
"background-color: rgb(216, 216, 216);\n"
"\n"
"}")
        self.frame_4.setFrameShape(QFrame.NoFrame)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QLabel(self.frame)
        self.label.setGeometry(QRect(10, 10, 300, 300))
        self.label.setText("")
        self.label.setTextFormat(Qt.RichText)
        self.label.setPixmap(QPixmap("Tachlinesr.png"))
        self.label.setObjectName("label")
        self.label_2 = QLabel(self.frame)
        self.label_2.setGeometry(QRect(10, -15, 300, 300))
        self.label_2.setText("")
        self.label_2.setTextFormat(Qt.RichText)
        self.label_2.setPixmap(QPixmap("RPM numbers resize.png"))
        self.label_2.setObjectName("label_2")
        self.Needle = QLabel(self.frame)
        self.Needle.setGeometry(QRect(10, 10, 300, 300))
        self.Needle.setStyleSheet("")
        self.Needle.setText("")
        self.Needle.setTextFormat(Qt.RichText)
        self.Needle.setPixmap(QPixmap("needle3.png"))
        self.Needle.setAlignment(Qt.AlignCenter)
        self.Needle.setObjectName("Needle")
        self.RPMtext = QLabel(self.frame)
        self.RPMtext.setGeometry(QRect(105, 250, 100, 50))
        font = QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.RPMtext.setFont(font)
        self.RPMtext.setStyleSheet("")
        self.RPMtext.setAlignment(Qt.AlignCenter)
        self.RPMtext.setObjectName("RPMtext")
        self.label_3 = QLabel(self.frame)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QRect(10, 10, 300, 300))
        self.label_3.setText("")
        self.label_3.setPixmap(QPixmap("Pointer2.png"))
        self.label_3.setObjectName("label_3")
        self.frame_4.raise_()
        self.frame_3.raise_()
        self.frame_2.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.Needle.raise_()
        self.RPMtext.raise_()
        self.label_3.raise_()

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.RPMtext.setText(_translate("Form", "13000"))
