# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Speedometerwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class SpeedoQT(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(596, 432)
        self.frame = QFrame(Form)
        self.frame.setGeometry(QRect(10, 10, 320, 320))
        self.frame.setFrameShape(QFrame.NoFrame)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setGeometry(QRect(10, 10, 300, 300))
        self.frame_2.setStyleSheet("background-color: rgb(216, 216, 216);")
        self.frame_2.setFrameShape(QFrame.NoFrame)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QFrame(self.frame)
        self.frame_3.setGeometry(QRect(10, 10, 300, 300))
        self.frame_3.setStyleSheet("QFrame{\n"
"\n"
"border-radius: 150px;\n"
"    background-color: rgb(247, 247, 247);\n"
"\n"
"}")
        self.frame_3.setFrameShape(QFrame.NoFrame)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_4 = QFrame(self.frame)
        self.frame_4.setGeometry(QRect(15, 15, 290, 290))
        self.frame_4.setStyleSheet("QFrame{\n"
"\n"
"border-radius: 145px;\n"
"    background-color: rgb(0,0,0);\n"
"\n"
"}")
        self.frame_4.setFrameShape(QFrame.NoFrame)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label = QLabel(self.frame)
        self.label.setGeometry(QRect(10, 10, 300, 300))
        self.label.setText("")
        self.label.setTextFormat(Qt.RichText)
        self.label.setPixmap(QPixmap("speedolines2.png"))
        self.label.setObjectName("label")
        self.label_2 = QLabel(self.frame)
        self.label_2.setGeometry(QRect(10, -25, 300, 300))
        self.label_2.setText("")
        self.label_2.setPixmap(QPixmap("Speedometer2.png"))
        self.label_2.setObjectName("label_2")
        self.Needle = QLabel(self.frame)
        self.Needle.setGeometry(QRect(60, 60, 200, 200))
        self.Needle.setText("")
        self.Needle.setPixmap(QPixmap("needle3.png"))
        self.Needle.setAlignment(Qt.AlignCenter)
        self.Needle.setObjectName("Needle")
        self.label_4 = QLabel(self.frame)
        self.label_4.setGeometry(QRect(10, 60, 200, 200))
        self.label_4.setText("")
        self.label_4.setPixmap(QPixmap("Pointer2.png"))
        self.label_4.setObjectName("label_4")
        self.label_3 = QLabel(self.frame)
        self.label_3.setGeometry(QRect(100, 225, 125, 50))
        font = QFont()
        font.setFamily("Bahnschrift SemiCondensed")
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.Needle.raise_()
        self.label_4.raise_()

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Bahnschrift SemiCondensed\'; font-size:24pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">100 kph</span></p></body></html>"))
