# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelemetryLoader.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *

class Ui_SplashScreen(object):
    def setupUi(self, SplashScreen):
        SplashScreen.setObjectName("SplashScreen")
        SplashScreen.resize(340, 340)
        self.Splash = QWidget(SplashScreen)
        self.Splash.setObjectName("Splash")
        self.SplashBase = QFrame(self.Splash)
        self.SplashBase.setGeometry(QRect(10, 10, 320, 320))
        self.SplashBase.setFrameShape(QFrame.NoFrame)
        self.SplashBase.setFrameShadow(QFrame.Raised)
        self.SplashBase.setObjectName("SplashBase")
        self.Circularvalue = QFrame(self.SplashBase)
        self.Circularvalue.setGeometry(QRect(10, 10, 300, 300))
        self.Circularvalue.setStyleSheet("QFrame {\n"
"border-radius: 150px;\n"
"background-color: qconicalgradient(cx:0.5, cy:0.5, angle:90, stop:0.749 rgba(255, 0, 127, 0), stop:0.75 rgba(0, 85, 255, 255));\n"
"}")
        self.Circularvalue.setFrameShape(QFrame.StyledPanel)
        self.Circularvalue.setFrameShadow(QFrame.Raised)
        self.Circularvalue.setObjectName("Circularvalue")
        self.Circularvaluebg = QFrame(self.SplashBase)
        self.Circularvaluebg.setGeometry(QRect(10, 10, 300, 300))
        self.Circularvaluebg.setStyleSheet("QFrame{\n"
"border-radius: 150px;\n"
"    background-color: rgba(0, 170, 0, 150);\n"
"}")
        self.Circularvaluebg.setFrameShape(QFrame.NoFrame)
        self.Circularvaluebg.setFrameShadow(QFrame.Raised)
        self.Circularvaluebg.setObjectName("Circularvaluebg")
        self.Overlay = QFrame(self.SplashBase)
        self.Overlay.setGeometry(QRect(35, 35, 250, 250))
        self.Overlay.setStyleSheet("QFrame{\n"
"border-radius: 125px;\n"
"    background-color: rgb(0, 0, 127);\n"
"}")
        self.Overlay.setFrameShape(QFrame.NoFrame)
        self.Overlay.setFrameShadow(QFrame.Raised)
        self.Overlay.setObjectName("Overlay")
        self.Image = QLabel(self.Overlay)
        self.Image.setGeometry(QRect(25, 75, 200, 100))
        font = QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Image.setFont(font)
        self.Image.setStyleSheet("background-color:none;\n"
"color: #FFFFFF")
        self.Image.setText("")
        self.Image.setTextFormat(Qt.RichText)
        self.Image.setPixmap(QPixmap("InstagramLogor.png"))
        self.Image.setAlignment(Qt.AlignCenter)
        self.Image.setObjectName("Image")
        self.Text = QLabel(self.Overlay)
        self.Text.setGeometry(QRect(40, 175, 175, 30))
        font = QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Text.setFont(font)
        self.Text.setStyleSheet("color: rgb(255, 255, 255);")
        self.Text.setObjectName("Text")
        self.Circularvaluebg.raise_()
        self.Circularvalue.raise_()
        self.Overlay.raise_()
        SplashScreen.setCentralWidget(self.Splash)

        self.retranslateUi(SplashScreen)
        QMetaObject.connectSlotsByName(SplashScreen)

    def retranslateUi(self, SplashScreen):
        _translate = QCoreApplication.translate
        SplashScreen.setWindowTitle(_translate("SplashScreen", "MainWindow"))
        self.Text.setText(_translate("SplashScreen", "Ogopogo Telemetry"))
